"""add_guide_number_to_deliveries

Revision ID: 0fd1c20c5786
Revises: 186ddffdd059
Create Date: 2026-06-03 14:01:10.161376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fd1c20c5786'
down_revision: Union[str, None] = '186ddffdd059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_records', sa.Column('guide_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_records', 'guide_number')
    # ### end Alembic commands ###
