"""drop_audit_log_user_fk

Revision ID: 5707d9fae95f
Revises: 5e3c5205a716
Create Date: 2026-06-12 13:00:07.245116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5707d9fae95f'
down_revision: Union[str, None] = '5e3c5205a716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
